version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && node src/index.js"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydb?schema=public"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
